### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by kane50613** [ConnorLinfoot/ActionBarAPI#18]
`[16:21:42 WARN]: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.null.entity.CraftPlayer
[16:21:42 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[16:21:42 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[16:21:42 WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[16:21:42 WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[16:21:42 WARN]: 	at java.lang.Class.forName0(Native Method)
[16:21:42 WARN]: 	at java.lang.Class.forName(Class.java:264)
[16:21:42 WARN]: 	at com.connorlinfoot.actionbarapi.ActionBarAPI.sendActionBar(ActionBarAPI.java:55)
[16:21:42 WARN]: 	at com.Kanetw.KanePlugin.commands.Vanish$1.run(Vanish.java:123)
[16:21:42 WARN]: 	at java.util.TimerThread.mainLoop(Timer.java:555)
[16:21:42 WARN]: 	at java.util.TimerThread.run(Timer.java:505)`
can you help me fix this? thanks :D

**Comment by Webbeh** [comment]
Describe your server setup

**Comment by TheFruxz** [comment]
I have the same issue too
