### ISSUE TITLE
java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by UnsocialDEV** [ConnorLinfoot/ActionBarAPI#30]
[14:52:29] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_16_R1.PacketPlayOutChat.<init>(net.minecraft.server.v1_16_R1.IChatBaseComponent, net.minecraft.server.v1_16_R1.ChatMessageType)
[14:52:29] [Server thread/WARN]:        at java.lang.Class.getConstructor0(Unknown Source)
[14:52:29] [Server thread/WARN]:        at java.lang.Class.getConstructor(Unknown Source)
[14:52:29] [Server thread/WARN]:        at com.connorlinfoot.actionbarapi.ActionBarAPI.sendActionBar(ActionBarAPI.java:79)
[14:52:29] [Server thread/WARN]:        at me.dayton.ActionBar.Events.PlayerMove.onPlayerMove(PlayerMove.java:15)
[14:52:29] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:52:29] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:52:29] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:52:29] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[14:52:29] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315)
[14:52:29] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:52:29] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[14:52:29] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[14:52:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1010)
[14:52:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInFlying.a(SourceFile:122)
[14:52:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56)
[14:52:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[14:52:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[14:52:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[14:52:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:52:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[14:52:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:941)
[14:52:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:934)
[14:52:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[14:52:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:918)
[14:52:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:850)
[14:52:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
[14:52:29] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by BluuKiwi** [comment]
same error, bump
